[package]
name = 'rsgeo'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'rsgeo'

[dependencies]
extendr-api = { version = '0.4.0'}
geo = "0.26.0"
geo-types = "0.7.8"
geojson = "0.24.0"
ndarray = "0.15.6"
rayon = "1.6.1"
rstar = "0.11.0"
serde_json = "1.0.92"
wkb = "0.7.1"
wkt = "0.10.3"
# sfconversions = { version = "0.2.0", git = "https://github.com/JosiahParry/sfconversions"}
sfconversions = { version = "0.2.0", path = "../../../sfconversions"}
num-traits = "0.2.15"
