[package]
name = 'rsgeo'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'rsgeo'

[dependencies]
extendr-api = '*'
geo = "0.23.1"
geo-types = "0.7.8"
ndarray = "0.15.6"
rstar = "0.9.3"
wkt = "0.10.3"
