# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rsgeo_wrappers", use_symbols = TRUE, package_name = "rsgeo")

#' @docType package
#' @usage NULL
#' @useDynLib rsgeo, .registration = TRUE
NULL

from_sfc <- function(x) .Call(wrap__from_sfc, x)

to_sfc <- function(x) .Call(wrap__to_sfc, x)

#' Find centroid
#' @param x an object of class `point`
#'@export
centroids <- function(x) .Call(wrap__centroids, x)

haversine_destination <- function(x, bearing, distance) .Call(wrap__haversine_destination, x, bearing, distance)

#' @param x an `rs_POINT` vector
#' @param y an `rs_POINT` vector
#' @param distance a numeric vector of either length 1 or the same length as x and y.
haversine_intermediate <- function(x, y, distance) .Call(wrap__haversine_intermediate, x, y, distance)

#'@export
signed_area <- function(x) .Call(wrap__signed_area, x)

#' @export
unsigned_area <- function(x) .Call(wrap__unsigned_area, x)

#' @export
signed_area_geodesic <- function(x) .Call(wrap__signed_area_geodesic, x)

#' @export
unsigned_area_geodesic <- function(x) .Call(wrap__unsigned_area_geodesic, x)

length_euclidean <- function(x) .Call(wrap__length_euclidean, x)

length_geodesic <- function(x) .Call(wrap__length_geodesic, x)

length_vincenty <- function(x) .Call(wrap__length_vincenty, x)

bearing_geodesic <- function(x, y) .Call(wrap__bearing_geodesic, x, y)

bearing_haversine <- function(x, y) .Call(wrap__bearing_haversine, x, y)

closest_point <- function(x, y) .Call(wrap__closest_point, x, y)

closest_point_haversine <- function(x, y) .Call(wrap__closest_point_haversine, x, y)

is_convex <- function(x) .Call(wrap__is_convex, x)

line_interpolate_point <- function(x, fraction) .Call(wrap__line_interpolate_point, x, fraction)

locate_point_on_line <- function(x, y) .Call(wrap__locate_point_on_line, x, y)

bounding_boxes <- function(x) .Call(wrap__bounding_boxes, x)

bounding_rect <- function(x) .Call(wrap__bounding_rect, x)

convex_hull <- function(x) .Call(wrap__convex_hull, x)

concave_hull <- function(x, concavity) .Call(wrap__concave_hull, x, concavity)

extreme_coords <- function(x) .Call(wrap__extreme_coords, x)

simplify_geoms <- function(x, epsilon) .Call(wrap__simplify_geoms, x, epsilon)

simplify_vw_geoms <- function(x, epsilon) .Call(wrap__simplify_vw_geoms, x, epsilon)

simplify_vw_preserve_geoms <- function(x, epsilon) .Call(wrap__simplify_vw_preserve_geoms, x, epsilon)

frechet_distance <- function(x, y) .Call(wrap__frechet_distance, x, y)

intersects_sparse <- function(x, y) .Call(wrap__intersects_sparse, x, y)

contains_sparse <- function(x, y) .Call(wrap__contains_sparse, x, y)

within_sparse <- function(x, y) .Call(wrap__within_sparse, x, y)

geom_point <- function(x, y) .Call(wrap__geom_point, x, y)

geom_multipoint <- function(x, y, id) .Call(wrap__geom_multipoint, x, y, id)

geom_linestring <- function(x, y, id) .Call(wrap__geom_linestring, x, y, id)

geom_polygon <- function(x, y, id, ring) .Call(wrap__geom_polygon, x, y, id, ring)

#' @export
#' @rdname combine_geoms
union_geoms <- function(x) .Call(wrap__union_geoms, x)

null_pntr <- function() .Call(wrap__null_pntr)

print_geom <- function(x) .Call(wrap__print_geom, x)

cast_points <- function(x, to) .Call(wrap__cast_points, x, to)

cast_multipoints <- function(x, to) .Call(wrap__cast_multipoints, x, to)

cast_linestrings <- function(x, to) .Call(wrap__cast_linestrings, x, to)

cast_multilinestrings <- function(x, to) .Call(wrap__cast_multilinestrings, x, to)

cast_polygons <- function(x, to) .Call(wrap__cast_polygons, x, to)

cast_multipolygons <- function(x, to) .Call(wrap__cast_multipolygons, x, to)

expand_linestring <- function(x) .Call(wrap__expand_linestring, x)

expand_multipolygon <- function(x) .Call(wrap__expand_multipolygon, x)

expand_multilinestring <- function(x) .Call(wrap__expand_multilinestring, x)

expand_multipoint <- function(x) .Call(wrap__expand_multipoint, x)

expand_polygon <- function(x) .Call(wrap__expand_polygon, x)

expand_geoms <- function(x) .Call(wrap__expand_geoms, x)

combine_points <- function(x) .Call(wrap__combine_points, x)

combine_multipoints <- function(x) .Call(wrap__combine_multipoints, x)

combine_linestrings <- function(x) .Call(wrap__combine_linestrings, x)

combine_multilinestrings <- function(x) .Call(wrap__combine_multilinestrings, x)

combine_polygons <- function(x) .Call(wrap__combine_polygons, x)

combine_multipolygons <- function(x) .Call(wrap__combine_multipolygons, x)

point_to_coords <- function(x) .Call(wrap__point_to_coords, x)

multipoint_to_coords <- function(x) .Call(wrap__multipoint_to_coords, x)

linestring_to_coords <- function(x) .Call(wrap__linestring_to_coords, x)

multilinestring_to_coords <- function(x) .Call(wrap__multilinestring_to_coords, x)

polygon_to_coords <- function(x) .Call(wrap__polygon_to_coords, x)

multipolygon_to_coords <- function(x) .Call(wrap__multipolygon_to_coords, x)


# nolint end
